---
# tasks file for pgadmin_role
#
#
- name: "Ajout du template pgadmin  docker-compose.yml"
  template:
    src: "docker-compose.yml.j2"
    dest: /home/{{ ansible_user }}/docker-compose.yml

- name: "Ajout du template servers.json"
  template:
    src: "servers.json.j2"
    dest: /home/{{ ansible_user }}/servers.json


- name: "Lancer le fichier docker-compose.yml"
  docker_compose:
    project_src: /home/{{ ansible_user }}
    files:
    - docker-compose.yml

